services:
  chirpstack:
    build:
      context: .
      dockerfile: Dockerfile-devel
    volumes:
      - ./:/chirpstack
      - ./.rust/target:/chirpstack/target
      - ./.rust/.cargo/registry/index:/usr/local/cargo/registry/index
      - ./.rust/.cargo/registry/cache:/usr/local/cargo/registry/cache
      - ./.rust/.cargo/git/db:/usr/local/cargo/git/db
    depends_on:
      - postgres
      - redis
      - mosquitto
      - rabbitmq
      - kafka
    environment:
      - DATABASE_URL=postgres://chirpstack_test:chirpstack_test@postgres/chirpstack_test?sslmode=disable
      - REDIS_HOST=redis
      - POSTGRESQL_HOST=postgres
      - MQTT_BROKER_HOST=mosquitto
    ports:
      - "8080:8080"

  chirpstack-build-amd64:
    image: chirpstack/chirpstack-dev-cache:latest
    platform: linux/amd64
    volumes:
      - ./:/chirpstack

  chirpstack-build-arm64:
    image: chirpstack/chirpstack-dev-cache:latest
    platform: linux/arm64
    volumes:
      - ./:/chirpstack

  chirpstack-ui:
    build:
      context: ./ui
      dockerfile: Dockerfile-devel
    volumes:
      - ./api/grpc-web:/chirpstack/api/grpc-web
      - ./ui:/chirpstack/ui
    ports:
      - "3000:3000"

  postgres:
    image: postgres:11-alpine
    volumes:
      - ./.docker-compose/postgresql/initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: redis:6-alpine

  mosquitto:
    image: eclipse-mosquitto:1.6
    ports:
      - "1883:1883"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"

  zookeeper:
    image: 'bitnami/zookeeper:3'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:3'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
